### ISSUE TITLE
icon not showing 

### ISSUE THREAD

**Issue by ayushnau** [fossasia/fossasia.org#835] opened 2021-08-11 12:53 UTC
![fossasiaerror](https://user-images.githubusercontent.com/78146753/129031807-fefdf64e-cbfd-427e-b55d-3b90d7ea5215.png)

**Comment by SamarthAroraa** [comment] 2021-08-26 23:05
Hi, @Ayush2020012016 I was not able to reproduce the issue. Could you include steps to reproduce the issue?

**Comment by imthegithubuser** [comment] 2021-09-05 11:06
can i work on this issue?

**Comment by abishekvashok** [comment] 2021-09-06 05:03
Closing as not reproducable

**Closed as completed by abishekvashok** 2021-09-06 05:03 UTC
