### ISSUE TITLE
Padding required between text fields and button in subscription form.

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/fossasia.org#312] opened 2018-09-12 10:31 UTC
**Actual Behaviour**
Padding is not present between text fields and button in subscription form.

![screen shot 2018-09-12 at 3 55 47 pm](https://user-images.githubusercontent.com/31539812/45419251-60386300-b6a4-11e8-857e-656bbd2095b1.png)

**Expected behaviour:**
Padding is required between text fields and button in subscription form.

**Would you like to work on the issue?**
No

**Comment by rohitjain00** [comment] 2018-09-16 02:52
Can I solve the issue?

**Comment by neeraj3029** [comment] 2018-09-16 06:04
@rohitjain00 I will be working on this issue.

**Comment by neeraj3029** [comment] 2018-09-18 07:17
@rohitjain00 I won't be working on this issue now. You can get it assigned.

**Comment by Ridvmodi** [comment] 2018-09-23 06:58
Can I work on this issue?

**Comment by rohitjain00** [comment] 2018-09-23 17:42
@Ridvmodi yes just submit a PR

**Comment by Ridvmodi** [comment] 2018-09-23 17:53
The subscribe form was removed now @rohitjain00

**Comment by siddhantshukla-10** [comment] 2018-10-01 18:05
Is this issue still open?
If yes, I want to work on it.

**Comment by sahilBhola98** [comment] 2018-10-13 10:27
can i work on this?

**Comment by Ridvmodi** [comment] 2018-10-13 14:59
The issue is removed. please close this issue @neeraj3029 .

**Closed as completed** 2018-10-25 08:53 UTC
