### ISSUE TITLE
highlight the nav links

### ISSUE THREAD

**Issue by Dilshan1997** [fossasia/fossasia.org#697] opened 2020-05-01 13:45 UTC
I suppose it is very important to access the links.

**Comment by Chaitanyassr** [comment] 2020-05-02 05:30
> I suppose it is very important to access the links.

Hi @Dilshan1997 , Please be more clear and specific about the issue. attach a screenshot and what do you mean by accessing the link. Which link you are talking about etc.

**Comment by Dilshan1997** [comment] 2020-05-04 04:53
![image](https://user-images.githubusercontent.com/48722230/80937019-004e7d00-8df1-11ea-951f-1a0271cb69d3.png)

that nav links highlight.

**Comment by Deeksha2501** [comment] 2020-05-06 23:21
I would like to work on the issue

**Comment by Chaitanyassr** [comment] 2020-05-06 23:31
Hi @Deeksha2501 , A PR is already there for this issue also and it is approved by 2 members. it would be suggested to hold of for this issue.

**Comment by keshavagarwal17** [comment] 2020-05-07 08:37
is this issue is open? I would like to work on it.

**Comment by Dilshan1997** [comment] 2020-05-07 08:40
yes this issue is open.you can contribut to it

**Comment by keshavagarwal17** [comment] 2020-05-07 08:51
thanks. i am going to start work on it.

**Comment by Pranav-Kumar-Rai** [comment] 2020-05-07 09:01
Can i work on it?

**Comment by Chaitanyassr** [comment] 2020-05-07 09:04
> ![image](https://user-images.githubusercontent.com/48722230/80937019-004e7d00-8df1-11ea-951f-1a0271cb69d3.png)
> 
> that nav links highlight.

Are you saying that you want to highlight , projects, events, shop, blog and all. correct me if i am wrong?

**Comment by Pranav-Kumar-Rai** [comment] 2020-05-07 09:08
Yes I want to work on that but i am beginner.

**Comment by keshavagarwal17** [comment] 2020-05-07 09:17
but i am working on it

**Comment by Dilshan1997** [comment] 2020-05-07 09:21
> > ![image](https://user-images.githubusercontent.com/48722230/80937019-004e7d00-8df1-11ea-951f-1a0271cb69d3.png)
> > that nav links highlight.
> 
> Are you saying that you want to highlight , projects, events, shop, blog and all. correct me if i am wrong?

Yeah your right

**Comment by keshavagarwal17** [comment] 2020-05-07 09:38
![Screenshot (248)](https://user-images.githubusercontent.com/56120769/81279281-8b8b7500-9074-11ea-9025-24ee6c969127.png)

is it fine?

**Comment by Dilshan1997** [comment] 2020-05-07 09:42
I suppose change the background colour of navs most usable..not only the nav link front colour

**Comment by keshavagarwal17** [comment] 2020-05-07 09:48
you want to change the background color of nav link always or only on hover??

**Comment by Dilshan1997** [comment] 2020-05-07 09:49
Only hover.

**Comment by keshavagarwal17** [comment] 2020-05-07 09:58
can you please tell me the html file name or folder name in which this file exist of navbar part.

**Comment by Pranav-Kumar-Rai** [comment] 2020-05-07 10:11
![fossAsia](https://user-images.githubusercontent.com/56068551/81282676-21c19a00-9079-11ea-9527-c0d6cda9a967.png)
Do you want something like this?

**Comment by Chaitanyassr** [comment] 2020-05-07 10:31
@Dilshan1997  @The-Keshav-Agarwal  @betrayer-beep @Deeksha2501  This issue is not a bug fix. This is a feature request. A new feature implementation requires the discussion first from the mentors . @mariobehling @abishekvashok @prateekiiest can someone please look at this issue. Is this required or not as I believe that this repository is inactive and not being maintained.

**Comment by Dilshan1997** [comment] 2020-05-07 10:38
Ok i request it..@chaitnyasr thanks explain that thing..

**Comment by Chaitanyassr** [comment] 2020-05-07 10:43
@Dilshan1997  Dont close the issue, i have tagged the mentors they would be reaching out soon. An issue can be a feature request or bug report.

**Closed as completed** 2020-09-28 16:47 UTC
