### ISSUE TITLE
There Should be a class in for each images so that devs can easily customize and update the website

### ISSUE THREAD

**Issue by Abhigyankrsingh** [fossasia/fossasia.org#797] opened 2020-10-26 10:39 UTC

**Comment by Gupta-Nikhil85** [comment] 2020-10-29 12:10
can i work on it?

**Comment by Abhigyankrsingh** [comment] 2020-10-29 16:25
@Gupta-Nikhil85  Sorry,you can not work because i have already added, you can work on other issues

**Comment by Raunaksingh100** [comment] 2020-11-17 09:19
this is not a bug you can close this issue thanks.

**Closed as completed** 2020-11-17 10:43 UTC
